name: Employee Management Frontend

on:
  push:
    branches: [ "main" ]
  

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.11.1]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v2.0
      with:
        envkey_REACT_APP_API_BASE_URL: ${{ secrets.REACT_APP_API_BASE_URL }}

    - name: Use Node ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - run: npm run build 
      env:
          CI: false
    - name: ssh deploy
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_DEPLOY_KEY_LIVE }}
          REMOTE_HOST: ${{ secrets.HOST_LIVE }}
          REMOTE_USER: ${{ secrets.USER }}
          TARGET: "/var/www/html/employee_front/"
          SOURCE: "build/*"
